In [1]:
file_path = "all_warehouses_cleaned_4000.kml"
fixed_path = "all_warehouses_fixed.kml"

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Strip leading whitespace/newlines and write to a new file
with open(fixed_path, 'w', encoding='utf-8') as f:
    f.write(content.lstrip())

print("File cleaned! Now try loading 'all_warehouses_fixed.kml'.")

File cleaned! Now try loading 'all_warehouses_fixed.kml'.

In [2]:
def export_chip(feature):
    geom = feature.geometry().buffer(100).bounds() # 100m buffer for the warehouse
    task = ee.batch.Export.image.toDrive(
        image=satellite_collection.median(),
        description=f"warehouse_{feature.id()}",
        region=geom,
        scale=1 # 1 meter per pixel
    )
    task.start()

In [9]:
%pip install geopandas fiona pyproj shapely rtree pyogrio

Requirement already satisfied: geopandas in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (1.1.2)
Requirement already satisfied: fiona in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (1.10.1)
Requirement already satisfied: pyproj in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (3.7.2)
Requirement already satisfied: shapely in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (2.1.2)
Requirement already satisfied: rtree in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (1.4.1)
Requirement already satisfied: pyogrio in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (0.12.1)
Requirement already satisfied: numpy>=1.24 in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (from geopandas) (2.3.5)
Requirement already satisfied: packaging in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (from geopandas) (26.0)
Requirement already satisfied: pandas>=2.0.0 in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (from geopandas) (2.3.3)
Requirement already satisfied: attrs>=19.2.0 in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (from fiona) (25.4.0)
Requirement already satisfied: certifi in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (from fiona) (2026.1.4)
Requirement already satisfied: click~=8.0 in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (from fiona) (8.3.1)
Requirement already satisfied: click-plugins>=1.0 in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (from fiona) (1.1.1.2)
Requirement already satisfied: cligj>=0.5 in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (from fiona) (0.7.2)
Requirement already satisfied: colorama in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (from click~=8.0->fiona) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\zz\desktop\school\scm 256\scm256-env\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import geopandas as gpd
gdf = gpd.read_file(kml_path, engine="pyogrio")

In [11]:
import fiona
print([k for k in fiona.supported_drivers.keys() if "KML" in k.upper()])

['KML']

In [13]:
from pathlib import Path
import geopandas as gpd
import fiona

cwd = Path.cwd()
print("Current working dir:", cwd)

kml_name = "all_warehouses_fixed.kml"
kml_path = cwd / kml_name

print("KML exists?", kml_path.exists(), kml_path)
if not kml_path.exists():
    raise FileNotFoundError(kml_path)

print("Fiona KML drivers:", [k for k in fiona.supported_drivers if "KML" in k.upper()])

# Prefer pyogrio first; fall back to fiona only if fiona advertises KML support
try:
    gdf = gpd.read_file(kml_path, engine="pyogrio")
    print("Loaded with pyogrio")
except Exception as pyogrio_err:
    print("pyogrio failed:", repr(pyogrio_err))
    fiona_has_kml = any("KML" in k.upper() for k in fiona.supported_drivers)
    if not fiona_has_kml:
        raise RuntimeError(
            "KML read failed: pyogrio failed and Fiona has no KML/LIBKML driver. "
            "Use conda-forge GDAL/Fiona build or convert KML to GeoJSON."
        ) from pyogrio_err
    gdf = gpd.read_file(kml_path, engine="fiona")
    print("Loaded with fiona")

print(gdf.head())
print("Rows:", len(gdf), "CRS:", gdf.crs)

Current working dir: c:\Users\zz\Desktop\school\SCM 256\final_proj\Loadsmart
KML exists? True c:\Users\zz\Desktop\school\SCM 256\final_proj\Loadsmart\all_warehouses_fixed.kml
Fiona KML drivers: ['KML']
Loaded with pyogrio
     id                                  Name  \
0  None  64ca7587-a0b0-49d4-b140-74d691d72465
1  None  5def5206-f194-471a-ad37-6799230ace36
2  None  0210fd59-e763-43de-ac46-9588cbc9a57b
3  None  3c45b517-3152-47bd-a79a-0eec76bd6714
4  None  4f273068-b659-4901-addf-c1f6b15d7b36

                                         description timestamp begin end  \
0  \n        <b>ID: 64ca7587-a0b0-49d4-b140-74d69...       NaT   NaT NaT
1  \n        <b>ID: 5def5206-f194-471a-ad37-67992...       NaT   NaT NaT
2  \n        <b>ID: 0210fd59-e763-43de-ac46-9588c...       NaT   NaT NaT
3  \n        <b>ID: 3c45b517-3152-47bd-a79a-0eec7...       NaT   NaT NaT
4  \n        <b>ID: 4f273068-b659-4901-addf-c1f6b...       NaT   NaT NaT

  altitudeMode  tessellate  extrude  visibility  drawOrder  icon  \
0         None          -1        0          -1        NaN  None
1         None          -1        0          -1        NaN  None
2         None          -1        0          -1        NaN  None
3         None          -1        0          -1        NaN  None
4         None          -1        0          -1        NaN  None

                          geometry
0   POINT Z (-83.97244 33.96621 0)
1  POINT Z (-112.00437 41.26256 0)
2    POINT Z (-96.66983 32.8584 0)
3   POINT Z (-97.09736 32.03513 0)
4   POINT Z (-84.18692 38.02415 0)
Rows: 351 CRS: EPSG:4326

In [14]:
import requests

key = "AIzaSyDndj9U6CdQYjH5UBSI13mGG-XVlX3bmp4"
url = f"https://maps.googleapis.com/maps/api/staticmap?center=40.7128,-74.0060&zoom=18&size=512x512&maptype=satellite&key={key}"
r = requests.get(url, timeout=20)
print(r.status_code, r.headers.get("content-type"), len(r.content))
print(r.text[:200] if "text" in (r.headers.get("content-type") or "") else "binary image")

200 image/png 203766
binary image

In [15]:
import os
import requests

os.makedirs("warehouse_dataset", exist_ok=True)

def download_tiles(gdf, api_key):
    for idx, row in gdf.iterrows():
        lat = row.geometry.y
        lon = row.geometry.x
        url = f"https://maps.googleapis.com/maps/api/staticmap?center={lat},{lon}&zoom=18&size=512x512&maptype=satellite&key={api_key}"
        r = requests.get(url, timeout=20)
        if r.status_code == 200:
            with open(f"warehouse_dataset/img_{idx}.jpg", "wb") as f:
                f.write(r.content)
        if idx % 50 == 0:
            print(f"Progress: {idx}/{len(gdf)}")

download_tiles(gdf, "AIzaSyDndj9U6CdQYjH5UBSI13mGG-XVlX3bmp4")

Progress: 0/351
Progress: 50/351
Progress: 100/351
Progress: 150/351
Progress: 200/351
Progress: 250/351
Progress: 300/351
Progress: 350/351

In [18]:
import os
files = os.listdir('warehouse_dataset')
print(f"Total files found: {len(files)}")
if len(files) > 0:
    print("First 5 files:", files[:5])

Total files found: 351
First 5 files: ['img_0.jpg', 'img_1.jpg', 'img_10.jpg', 'img_100.jpg', 'img_101.jpg']

In [19]:
import shutil
# format: make_archive('output_name', 'format', 'source_folder')
shutil.make_archive('warehouse_images', 'zip', 'warehouse_dataset')

'c:\\Users\\zz\\Desktop\\school\\SCM 256\\final_proj\\Loadsmart\\warehouse_images.zip'

In [20]:
import numpy as np

os.makedirs('negative_samples', exist_ok=True)

def download_negatives(gdf, api_key, offset_meters=800):
    # Degree approximation: 1 degree is roughly 111,000 meters
    deg_offset = offset_meters / 111000.0

    for idx, row in gdf.iterrows():
        # Randomly choose a direction to shift (North, South, East, or West)
        angle = np.random.uniform(0, 2 * np.pi)
        lat_offset = row.geometry.y + (deg_offset * np.sin(angle))
        lon_offset = row.geometry.x + (deg_offset * np.cos(angle))

        url = f"https://maps.googleapis.com/maps/api/staticmap?center={lat_offset},{lon_offset}&zoom=18&size=512x512&maptype=satellite&key={api_key}"

        response = requests.get(url)
        if response.status_code == 200:
            with open(f"negative_samples/neg_{idx}.jpg", "wb") as f:
                f.write(response.content)

        if idx % 50 == 0:
            print(f"Downloaded {idx} negative samples...")

In [ ]:
download_negatives(gdf, "AIzaSyDndj9U6CdQYjH5UBSI13mGG-XVlX3bmp4")

Downloaded 0 negative samples...
Downloaded 50 negative samples...
Downloaded 100 negative samples...
Downloaded 150 negative samples...
Downloaded 200 negative samples...
Downloaded 250 negative samples...
Downloaded 300 negative samples...
Downloaded 350 negative samples...

In [21]:
import os
import re
import json
import time
import math
import random
import requests
import numpy as np
import pandas as pd
from pathlib import Path

# ====== Experiment scale ======
TARGET_SAMPLE_SIZE = 1000

# Distance parameters for negative sample generation
MIN_OFFSET_M = 1500
MAX_OFFSET_M = 5000

# Places screening radius
PLACES_RADIUS_M = 300

# Semantic naming (no more v1/v2)
NEG_STRATEGY = f"random_offset_{MIN_OFFSET_M}_{MAX_OFFSET_M}m"
NEG_DIR = f"negative_samples_{NEG_STRATEGY}_{TARGET_SAMPLE_SIZE}"
META_DIR = f"metadata_{NEG_STRATEGY}_{TARGET_SAMPLE_SIZE}"
Path(NEG_DIR).mkdir(exist_ok=True)
Path(META_DIR).mkdir(exist_ok=True)

# Keywords for Stage 1 map screening
STRONG_WAREHOUSE_TERMS = [
    "warehouse", "distribution center", "fulfillment center",
    "logistics", "depot", "storage", "freight", "crossdock", "cross dock"
]
SOFT_RISK_TERMS = [
    "industrial", "business park", "supply", "truck", "shipping", "terminal"
]

# ====== Auto-detect existing Google key variables (Static Maps key) ======
GOOGLE_KEY = "AIzaSyDndj9U6CdQYjH5UBSI13mGG-XVlX3bmp4"
for k in ["GOOGLE_STATIC_MAP_KEY", "MAPS_API_KEY", "GOOGLE_MAPS_API_KEY", "api_key"]:
    if k in globals() and isinstance(globals()[k], str) and len(globals()[k]) > 20:
        GOOGLE_KEY = globals()[k]
        print(f"Found Google key from variable: {k}")
        break

if GOOGLE_KEY is None:
    print("Google key was not auto-detected. Please set: GOOGLE_KEY = 'your_key'")
else:
    print("Google key ready")

# ====== OpenAI key (set environment variable if not set already) ======
os.environ["OPENAI_API_KEY"] = "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"
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", None)
print("OpenAI key ready:", OPENAI_API_KEY is not None)

# Check gdf
print("gdf exists:", "gdf" in globals())
if "gdf" in globals():
    print("gdf rows:", len(gdf))
    print("target sample size:", TARGET_SAMPLE_SIZE)
    if TARGET_SAMPLE_SIZE > len(gdf):
        print("Sampling with replacement will be used to reach the target sample size.")

Google key ready
OpenAI key ready: True
gdf exists: True
gdf rows: 351
target sample size: 1000
当前将使用有放回抽样，以达到目标样本数。

In [23]:
def random_offset_latlon(lat, lon, min_m=1500, max_m=5000):
    d = random.uniform(min_m, max_m)
    theta = random.uniform(0, 2 * math.pi)

    dlat = (d / 111000.0) * math.sin(theta)
    # Apply latitude-aware correction for longitude conversion
    dlon = (d / (111000.0 * max(math.cos(math.radians(lat)), 1e-6))) * math.cos(theta)

    return lat + dlat, lon + dlon, d


def download_static_satellite(lat, lon, api_key, zoom=18, size="512x512"):
    url = (
        "https://maps.googleapis.com/maps/api/staticmap"
        f"?center={lat},{lon}&zoom={zoom}&size={size}&maptype=satellite&key={api_key}"
    )
    r = requests.get(url, timeout=20)
    return r


assert "gdf" in globals(), "gdf is missing. Run the KML loading cell first."
assert TARGET_SAMPLE_SIZE > 0, "TARGET_SAMPLE_SIZE must be greater than 0"

neg_records = []
source_n = len(gdf)
sample_n = TARGET_SAMPLE_SIZE

# Sampling with replacement allows reaching 1000 even when gdf has 351 rows
sampled_indices = np.random.choice(source_n, size=sample_n, replace=True)

for i, src_idx in enumerate(sampled_indices):
    row = gdf.iloc[int(src_idx)]
    base_lat = float(row.geometry.y)
    base_lon = float(row.geometry.x)

    neg_lat, neg_lon, offset_m = random_offset_latlon(base_lat, base_lon, MIN_OFFSET_M, MAX_OFFSET_M)
    resp = download_static_satellite(neg_lat, neg_lon, GOOGLE_KEY)

    img_path = f"{NEG_DIR}/neg_{i}.jpg"
    ok = (resp.status_code == 200 and "image" in resp.headers.get("content-type", ""))

    if ok:
        with open(img_path, "wb") as f:
            f.write(resp.content)

    neg_records.append({
        "neg_id": i,
        "src_idx": int(src_idx),
        "src_lat": base_lat,
        "src_lon": base_lon,
        "neg_lat": neg_lat,
        "neg_lon": neg_lon,
        "offset_m": offset_m,
        "img_path": img_path,
        "img_download_ok": ok,
        "img_status_code": resp.status_code,
        "img_content_type": resp.headers.get("content-type", "")
    })

    if i % 100 == 0:
        print(f"Generated {i}/{sample_n}")

neg_df = pd.DataFrame(neg_records)
neg_meta_path = f"{META_DIR}/neg_candidates_{NEG_STRATEGY}_{sample_n}.csv"
neg_df.to_csv(neg_meta_path, index=False)

print("Done.")
print("Source gdf rows:", source_n)
print("Target candidates:", sample_n)
print("Actual generated:", len(neg_df))
print("Image downloaded:", int(neg_df["img_download_ok"].sum()))
print("Negative image folder:", NEG_DIR)
print("Metadata csv:", neg_meta_path)
print(neg_df.head(3))

Generated 0/1000
Generated 100/1000
Generated 200/1000
Generated 300/1000
Generated 400/1000
Generated 500/1000
Generated 600/1000
Generated 700/1000
Generated 800/1000
Generated 900/1000
Done.
Source gdf rows: 351
Target candidates: 1000
Actual generated: 1000
Image downloaded: 1000
Negative image folder: negative_samples_random_offset_1500_5000m_1000
Metadata csv: metadata_random_offset_1500_5000m_1000/neg_candidates_random_offset_1500_5000m_1000.csv
   neg_id  src_idx    src_lat     src_lon    neg_lat     neg_lon     offset_m  \
0       0      170  41.801021  -88.293704  41.784004  -88.280573  2179.080805
1       1       69  36.706028 -119.748345  36.683069 -119.764812  2939.705335
2       2       29  33.423744  -84.150201  33.453678  -84.174293  4002.775691

                                            img_path  img_download_ok  \
0  negative_samples_random_offset_1500_5000m_1000...             True
1  negative_samples_random_offset_1500_5000m_1000...             True
2  negative_samples_random_offset_1500_5000m_1000...             True

   img_status_code img_content_type
0              200        image/png
1              200        image/png
2              200        image/png

In [ ]:
# Cell 3: Map API category screening (Stage 1, safety-controlled dry run)
# Runs only 100 samples by default. Switch to full run after validation.

import json
import time
import requests
import pandas as pd

assert "neg_df" in globals(), "neg_df is missing. Run the previous negative-sample cell first."
assert "GOOGLE_KEY" in globals() and GOOGLE_KEY, "GOOGLE_KEY is missing. Run the config cell first."

# ===== Safety switches (small-sample first) =====
DRY_RUN = True               # True: run safety test on small sample
DRY_RUN_SIZE = 100           # dry-run sample size
FULL_RUN_SIZE = 1000         # full-run upper bound
ALLOW_FULL_RUN = False       # keep False until dry run is validated

# Places API parameters
PLACES_RADIUS_M = 300
PLACES_LIMIT_TOPK = 10

# Strong-risk keywords: direct remove when matched
STRONG_WAREHOUSE_TERMS = [
    "warehouse", "distribution center", "fulfillment center", "fulfilment center",
    "logistics", "depot", "storage", "freight", "crossdock", "cross dock"
]

# Soft-risk keywords: move to review bucket (next-stage LLM)
SOFT_RISK_TERMS = [
    "industrial", "business park", "supply", "truck", "shipping", "terminal"
]


def nearby_places(lat, lon, api_key, radius=300):
    url = (
        "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
        f"?location={lat},{lon}&radius={radius}&key={api_key}"
    )
    r = requests.get(url, timeout=25)
    if r.status_code != 200:
        return {
            "http_status": r.status_code,
            "places_status": "HTTP_ERROR",
            "results": []
        }
    data = r.json()
    return {
        "http_status": 200,
        "places_status": data.get("status", "UNKNOWN"),
        "results": data.get("results", [])
    }


def keyword_hits(text_blob, keywords):
    t = (text_blob or "").lower()
    return [kw for kw in keywords if kw in t]


# ===== Select run subset =====
if DRY_RUN:
    run_size = min(DRY_RUN_SIZE, len(neg_df))
    stage1_input_df = neg_df.head(run_size).copy()
    run_tag = f"dryrun_{run_size}"
else:
    run_size = min(FULL_RUN_SIZE, len(neg_df))
    if run_size > DRY_RUN_SIZE and not ALLOW_FULL_RUN:
        raise ValueError(
            f"Full mode selected with {run_size} planned Places API calls. "
            "Set ALLOW_FULL_RUN=True before running."
        )
    stage1_input_df = neg_df.head(run_size).copy()
    run_tag = f"fullrun_{run_size}"

print(f"[Stage1] Run tag: {run_tag}")
print(f"[Stage1] Planned Places API calls: {len(stage1_input_df)}")
print("[Stage1] Validate dry-run outputs first, then enable full run.")

stage1_records = []

for i, row in stage1_input_df.iterrows():
    lat, lon = float(row["neg_lat"]), float(row["neg_lon"])

    resp = nearby_places(lat, lon, GOOGLE_KEY, radius=PLACES_RADIUS_M)
    places = resp["results"][:PLACES_LIMIT_TOPK]

    poi_items = []
    blob = ""
    for p in places:
        name = p.get("name", "")
        types = p.get("types", [])
        types_text = ",".join(types)
        one = f"{name} | {types_text}"
        poi_items.append(one)
        blob += " " + one.lower()

    strong_hits = keyword_hits(blob, STRONG_WAREHOUSE_TERMS)
    soft_hits = keyword_hits(blob, SOFT_RISK_TERMS)

    if len(strong_hits) > 0:
        stage1_decision = "remove_by_map_strong"
    elif len(soft_hits) > 0:
        stage1_decision = "review_by_map_soft"
    else:
        stage1_decision = "keep_after_map"

    stage1_records.append({
        **row.to_dict(),
        "places_http_status": resp["http_status"],
        "places_status": resp["places_status"],
        "places_count_topk": len(places),
        "poi_topk": json.dumps(poi_items, ensure_ascii=False),
        "map_strong_hits": json.dumps(strong_hits, ensure_ascii=False),
        "map_soft_hits": json.dumps(soft_hits, ensure_ascii=False),
        "stage1_decision": stage1_decision,
        "run_tag": run_tag
    })

    if len(stage1_records) % 50 == 0:
        print(f"Stage1 progress: {len(stage1_records)}/{len(stage1_input_df)}")
    time.sleep(0.03)


stage1_df = pd.DataFrame(stage1_records)

# Save full table and split outputs
stage1_all_path = f"{META_DIR}/stage1_map_screened_{NEG_STRATEGY}_{run_tag}.csv"
stage1_removed_path = f"{META_DIR}/stage1_removed_by_map_{NEG_STRATEGY}_{run_tag}.csv"
stage1_review_path = f"{META_DIR}/stage1_review_by_map_{NEG_STRATEGY}_{run_tag}.csv"
stage1_keep_path = f"{META_DIR}/stage1_keep_after_map_{NEG_STRATEGY}_{run_tag}.csv"

stage1_df.to_csv(stage1_all_path, index=False)
stage1_df[stage1_df["stage1_decision"] == "remove_by_map_strong"].to_csv(stage1_removed_path, index=False)
stage1_df[stage1_df["stage1_decision"] == "review_by_map_soft"].to_csv(stage1_review_path, index=False)
stage1_df[stage1_df["stage1_decision"] == "keep_after_map"].to_csv(stage1_keep_path, index=False)

# Summary statistics
c_removed = int((stage1_df["stage1_decision"] == "remove_by_map_strong").sum())
c_review = int((stage1_df["stage1_decision"] == "review_by_map_soft").sum())
c_keep = int((stage1_df["stage1_decision"] == "keep_after_map").sum())

print("\n=== Stage 1 (Map screening) Summary ===")
print("Run tag:", run_tag)
print("Total:", len(stage1_df))
print("remove_by_map_strong:", c_removed)
print("review_by_map_soft:", c_review)
print("keep_after_map:", c_keep)
print("\nSaved:")
print(stage1_all_path)
print(stage1_removed_path)
print(stage1_review_path)
print(stage1_keep_path)

cols_show = ["neg_id", "neg_lat", "neg_lon", "places_status", "map_strong_hits", "map_soft_hits", "poi_topk"]
print("\nRemoved sample examples (top 10):")
display(stage1_df[stage1_df["stage1_decision"] == "remove_by_map_strong"][cols_show].head(10))

print("\nReview sample examples (top 10):")
display(stage1_df[stage1_df["stage1_decision"] == "review_by_map_soft"][cols_show].head(10))

[Stage1] Run tag: dryrun_100
[Stage1] Planned Places API calls: 100
[Stage1] 建议先确认 dry-run 输出无误，再开启全量。
Stage1 progress: 50/100
Stage1 progress: 100/100

=== Stage 1 (Map 初筛) Summary ===
Run tag: dryrun_100
Total: 100
remove_by_map_strong: 8
review_by_map_soft: 2
keep_after_map: 90

Saved:
metadata_random_offset_1500_5000m_1000/stage1_map_screened_random_offset_1500_5000m_dryrun_100.csv
metadata_random_offset_1500_5000m_1000/stage1_removed_by_map_random_offset_1500_5000m_dryrun_100.csv
metadata_random_offset_1500_5000m_1000/stage1_review_by_map_random_offset_1500_5000m_dryrun_100.csv
metadata_random_offset_1500_5000m_1000/stage1_keep_after_map_random_offset_1500_5000m_dryrun_100.csv

Removed sample examples (top 10):

,neg_id,neg_lat,neg_lon,places_status,map_strong_hits,map_soft_hits,poi_topk
1,1,36.683069,-119.764812,OK,"[""warehouse"", ""storage""]",[],"[""Fresno | locality,political"", ""Orange - Amaz..."
27,27,39.317564,-76.508384,OK,"[""storage""]",[],"[""Rosedale | locality,political"", ""Regal Inn &..."
35,35,41.668390,-88.137050,OK,"[""storage""]",[],"[""Bolingbrook | locality,political"", ""Crossroa..."
40,40,46.746929,-92.143061,OK,"[""warehouse"", ""storage""]","[""industrial""]","[""Duluth | locality,political"", ""Industrial We..."
47,47,34.053186,-117.510282,OK,"[""logistics"", ""storage""]",[],"[""Fontana | locality,political"", ""DCG Fulfillm..."
57,57,43.145084,-88.181286,OK,"[""storage""]",[],"[""Lisbon | locality,political"", ""Carl's Lawn M..."
82,82,33.783621,-84.621498,OK,"[""storage""]","[""industrial""]","[""Douglasville | locality,political"", ""Taylor ..."
93,93,39.014958,-94.669759,OK,"[""storage""]",[],"[""Overland Park | locality,political"", ""Econo ..."

Review sample examples (top 10):

,neg_id,neg_lat,neg_lon,places_status,map_strong_hits,map_soft_hits,poi_topk
15,15,34.023539,-117.462814,OK,[],"[""truck""]","[""Jurupa Valley | locality,political"", ""Auto G..."
56,56,41.826714,-87.729000,OK,[],"[""supply""]","[""Chicago | locality,political"", ""TKX Transpor..."

In [25]:
# Cell 4: Create manual review folders (copy images by Stage1 result)
# This copies files only and does not move original images.

from pathlib import Path
import pandas as pd
import shutil

assert "META_DIR" in globals(), "META_DIR is missing. Run the config cell first."

# Default to the latest dry-run output
RUN_TAG = "dryrun_100"
stage1_csv = Path(META_DIR) / f"stage1_map_screened_{NEG_STRATEGY}_{RUN_TAG}.csv"

if not stage1_csv.exists():
    raise FileNotFoundError(f"Stage1 output file not found: {stage1_csv}")

stage1_df = pd.read_csv(stage1_csv)

manual_root = Path(META_DIR) / f"manual_review_{NEG_STRATEGY}_{RUN_TAG}"
removed_dir = manual_root / "removed_by_map"
review_dir = manual_root / "review_by_map"
keep_dir = manual_root / "keep_after_map"

for d in [removed_dir, review_dir, keep_dir]:
    d.mkdir(parents=True, exist_ok=True)


def copy_group(df, target_dir):
    copied = 0
    missed = 0
    for _, r in df.iterrows():
        src = Path(str(r["img_path"]))
        if src.exists():
            # Prefix with neg_id to avoid accidental filename collisions
            dst = target_dir / f"neg_{int(r['neg_id'])}_{src.name}"
            shutil.copy2(src, dst)
            copied += 1
        else:
            missed += 1
    return copied, missed

removed_df = stage1_df[stage1_df["stage1_decision"] == "remove_by_map_strong"].copy()
review_df = stage1_df[stage1_df["stage1_decision"] == "review_by_map_soft"].copy()
keep_df = stage1_df[stage1_df["stage1_decision"] == "keep_after_map"].copy()

removed_copied, removed_missed = copy_group(removed_df, removed_dir)
review_copied, review_missed = copy_group(review_df, review_dir)
keep_copied, keep_missed = copy_group(keep_df, keep_dir)

summary = {
    "stage1_csv": str(stage1_csv),
    "manual_root": str(manual_root),
    "removed_count": int(len(removed_df)),
    "review_count": int(len(review_df)),
    "keep_count": int(len(keep_df)),
    "removed_copied": int(removed_copied),
    "review_copied": int(review_copied),
    "keep_copied": int(keep_copied),
    "removed_missed": int(removed_missed),
    "review_missed": int(review_missed),
    "keep_missed": int(keep_missed),
}

print("Manual review folder ready:")
for k, v in summary.items():
    print(f"- {k}: {v}")

# Optional: export manifests for cross-checking
removed_df.to_csv(manual_root / "removed_manifest.csv", index=False)
review_df.to_csv(manual_root / "review_manifest.csv", index=False)
keep_df.to_csv(manual_root / "keep_manifest.csv", index=False)
print("\nManifest files saved in manual_root.")

Manual review folder ready:
- stage1_csv: metadata_random_offset_1500_5000m_1000\stage1_map_screened_random_offset_1500_5000m_dryrun_100.csv
- manual_root: metadata_random_offset_1500_5000m_1000\manual_review_random_offset_1500_5000m_dryrun_100
- removed_count: 8
- review_count: 2
- keep_count: 90
- removed_copied: 8
- review_copied: 2
- keep_copied: 90
- removed_missed: 0
- review_missed: 0
- keep_missed: 0

Manifest files saved in manual_root.

In [ ]:
# Cell 5: Map screening (single-standard version, lower false removal risk)
# Different from the previous version: no direct remove, only high_risk / review / keep.

import json
import time
import requests
import pandas as pd
from pathlib import Path

assert "neg_df" in globals(), "neg_df is missing. Run the negative sample generation cell first."
assert "GOOGLE_KEY" in globals() and GOOGLE_KEY, "GOOGLE_KEY is missing. Run the config cell first."
assert "META_DIR" in globals(), "META_DIR is missing. Run the config cell first."

# Safety-test parameters
DRY_RUN = True
DRY_RUN_SIZE = 100
FULL_RUN_SIZE = 1000
ALLOW_FULL_RUN = False

PLACES_RADIUS_M = 300
PLACES_LIMIT_TOPK = 10

# Single-standard core terms (no direct delete, only high-risk label)
CORE_WAREHOUSE_TERMS = [
    "warehouse", "distribution center", "fulfillment center", "fulfilment center"
]

RELATED_TERMS = [
    "logistics", "depot", "freight", "crossdock", "cross dock", "storage"
]

SOFT_CONTEXT_TERMS = [
    "industrial", "business park", "truck", "shipping", "terminal", "supply"
]


def nearby_places(lat, lon, api_key, radius=300):
    url = (
        "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
        f"?location={lat},{lon}&radius={radius}&key={api_key}"
    )
    r = requests.get(url, timeout=25)
    if r.status_code != 200:
        return {"http_status": r.status_code, "places_status": "HTTP_ERROR", "results": []}
    data = r.json()
    return {
        "http_status": 200,
        "places_status": data.get("status", "UNKNOWN"),
        "results": data.get("results", [])
    }


def hits(text_blob, keywords):
    t = (text_blob or "").lower()
    return [kw for kw in keywords if kw in t]


if DRY_RUN:
    run_size = min(DRY_RUN_SIZE, len(neg_df))
    stage1_input_df = neg_df.head(run_size).copy()
    run_tag = f"dryrun_{run_size}_single_standard"
else:
    run_size = min(FULL_RUN_SIZE, len(neg_df))
    if run_size > DRY_RUN_SIZE and not ALLOW_FULL_RUN:
        raise ValueError(f"Planned {run_size} Places API calls. Set ALLOW_FULL_RUN=True first.")
    stage1_input_df = neg_df.head(run_size).copy()
    run_tag = f"fullrun_{run_size}_single_standard"

print(f"[Stage1-SS] Run tag: {run_tag}")
print(f"[Stage1-SS] Planned Places API calls: {len(stage1_input_df)}")

records = []
for n, (_, row) in enumerate(stage1_input_df.iterrows(), start=1):
    lat, lon = float(row["neg_lat"]), float(row["neg_lon"])
    resp = nearby_places(lat, lon, GOOGLE_KEY, radius=PLACES_RADIUS_M)
    places = resp["results"][:PLACES_LIMIT_TOPK]

    poi_items, blob = [], ""
    for p in places:
        name = p.get("name", "")
        types = ",".join(p.get("types", []))
        one = f"{name} | {types}"
        poi_items.append(one)
        blob += " " + one.lower()

    core_hits = hits(blob, CORE_WAREHOUSE_TERMS)
    rel_hits = hits(blob, RELATED_TERMS)
    soft_hits = hits(blob, SOFT_CONTEXT_TERMS)

    # Single-standard approach: no direct deletion, only risk-level routing
    if len(core_hits) > 0:
        decision = "high_risk_by_map"
    elif len(rel_hits) > 0 or len(soft_hits) > 0:
        decision = "review_by_map"
    else:
        decision = "keep_after_map"

    records.append({
        **row.to_dict(),
        "places_http_status": resp["http_status"],
        "places_status": resp["places_status"],
        "places_count_topk": len(places),
        "poi_topk": json.dumps(poi_items, ensure_ascii=False),
        "core_hits": json.dumps(core_hits, ensure_ascii=False),
        "related_hits": json.dumps(rel_hits, ensure_ascii=False),
        "soft_hits": json.dumps(soft_hits, ensure_ascii=False),
        "stage1_ss_decision": decision,
        "run_tag": run_tag
    })

    if n % 50 == 0:
        print(f"Stage1-SS progress: {n}/{len(stage1_input_df)}")
    time.sleep(0.03)

stage1_ss_df = pd.DataFrame(records)

base = Path(META_DIR)
all_path = base / f"stage1_ss_map_screened_{NEG_STRATEGY}_{run_tag}.csv"
high_path = base / f"stage1_ss_high_risk_{NEG_STRATEGY}_{run_tag}.csv"
review_path = base / f"stage1_ss_review_{NEG_STRATEGY}_{run_tag}.csv"
keep_path = base / f"stage1_ss_keep_{NEG_STRATEGY}_{run_tag}.csv"

stage1_ss_df.to_csv(all_path, index=False)
stage1_ss_df[stage1_ss_df["stage1_ss_decision"] == "high_risk_by_map"].to_csv(high_path, index=False)
stage1_ss_df[stage1_ss_df["stage1_ss_decision"] == "review_by_map"].to_csv(review_path, index=False)
stage1_ss_df[stage1_ss_df["stage1_ss_decision"] == "keep_after_map"].to_csv(keep_path, index=False)

print("\n=== Stage1 Single-Standard Summary ===")
print("Total:", len(stage1_ss_df))
print("high_risk_by_map:", int((stage1_ss_df["stage1_ss_decision"] == "high_risk_by_map").sum()))
print("review_by_map:", int((stage1_ss_df["stage1_ss_decision"] == "review_by_map").sum()))
print("keep_after_map:", int((stage1_ss_df["stage1_ss_decision"] == "keep_after_map").sum()))
print("\nSaved:")
print(all_path)
print(high_path)
print(review_path)
print(keep_path)